[phases.setup]
# Install system dependencies
apt_packages = ["python3", "python3-pip", "python3-dev", "gcc"]

[phases.build]
# Use pip3 explicitly
commands = [
  "pip3 install -r requirements.txt",
  "python3 setup.py install"
]

[start]
command = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600"
